### ISSUE TITLE
Negative List

### ISSUE THREAD

**Issue by yrmvgh** [nyanlathotep/dupefinder#1]
If a list's filename is NULL
or if a list begins with
NULL
Then that list is not used for dupefinder's results
instead any result from other lists that matches NULL is deleted/omitted

For instance, you run dupefinder on other people's cube lists, and use your own existing cube list as NULL so that dupefinder doesn't tell you about cards that you're already using.

**Comment by nyanlathotep** [comment]
probably will do this as flags that allow a group of a given name to be set as a whitelist/blacklist that will only/not show things in that group in the results

**Comment by yrmvgh** [comment]
That makes even more sense!

**Comment by nyanlathotep** [comment]
done, -f [groupname] will do a blacklist, -F [groupname] a whitelist
they're case-sensitive and can accept a substring at the beginning of the groupname, as long as that substring is unambiguous, e.g. if you have Blah and Blargh, "Blar" would match Blargh
